import Link from "next/link";
import type {LibraryBook} from "@/data/library";
export const seriesInfo={
"Biblical Discoveries":{tag:"SCRIPTURE STUDIES",description:"Short, carefully researched explorations of biblical details and the connections between passages.",tone:"discovery",symbol:"✧"},
"Children":{tag:"YOUNG READERS",description:"Gentle, age-appropriate Bible stories and questions to explore together.",tone:"children",symbol:"✦"},
"Prayers":{tag:"PRAYER & DEVOTION",description:"Biblically grounded prayers for repentance, intercession and standing firm in Christ.",tone:"prayer",symbol:"✳"}
} as const;
export type SeriesName=keyof typeof seriesInfo;
export function BookCover({book,large=false}:{book:LibraryBook;large?:boolean}){const info=seriesInfo[book.category],flagship=book.slug==="spiritual-warfare-standing-firm";return <div className={`uw2-cover uw2-cover--${info.tone} ${flagship?"uw2-cover--flagship":""} ${large?"uw2-cover--large":""}`} aria-label={book.title+" book cover"}><div className="uw2-cover-inner"><span className="uw2-cover-imprint">UNSEEN WAR <i>·</i> LIBRARY</span><div className="uw2-cover-art" aria-hidden="true"><svg viewBox="0 0 280 290" preserveAspectRatio="xMidYMid meet" role="img"><defs><linearGradient id={"sun-"+book.slug} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#fff9de" stopOpacity=".95"/><stop offset="100%" stopColor="#c9a76a" stopOpacity=".65"/></linearGradient></defs><path d="M25 272 V130 Q25 15 140 15 Q255 15 255 130 V272" stroke="currentColor" strokeOpacity=".5" strokeWidth="1.2" fill="none"/><path d="M45 272 V136 Q45 42 140 42 Q235 42 235 136 V272" stroke="currentColor" strokeOpacity=".3" strokeWidth=".8" fill="none"/><circle cx="140" cy="128" r="56" fill={"url(#sun-"+book.slug+")"}/><g stroke="#fff2c7" strokeOpacity=".7" strokeWidth="1.3">{Array.from({length:16},(_,i)=>{const a=i*Math.PI/8;return <line key={i} x1={140+Math.cos(a)*67} y1={128+Math.sin(a)*67} x2={140+Math.cos(a)*88} y2={128+Math.sin(a)*88}/>})}</g><path d="M35 240 Q89 191 140 229 Q187 190 245 240 L245 275 Q189 239 140 273 Q86 238 35 275Z" fill="#f2e7c7" fillOpacity=".86"/><path d="M140 229 V273 M42 242 Q88 214 135 242 M145 242 Q190 214 238 242" fill="none" stroke="#a88b60" strokeWidth="1.4"/></svg></div><div className="uw2-cover-bottom"><span className="uw2-cover-series">{flagship?"THE FLAGSHIP EDITION":info.tag}</span><strong>{book.title}</strong><span className="uw2-cover-footer">UNSEEN WAR  ·  SCRIPTURE & FAITH</span></div></div></div>}
export function BookTile({book}:{book:LibraryBook}){return <Link href={`/library/${book.slug}`} className="uw2-tile"><BookCover book={book}/><div className="uw2-tile-copy"><span className="uw2-label">{seriesInfo[book.category].tag} · {book.pages.length} SECTIONS</span><h3>{book.title}</h3><p>{book.description}</p><span className="uw2-text-link">Discover the book <span aria-hidden="true">↗</span></span></div></Link>}
